### ISSUE TITLE
Having issues in the s_flagManager.cs

### ISSUE THREAD

**Issue by Hassanali4** [PixelBrownieSoftware/Magnum-Foundation-experimental#1]
As there are 3 type of custom types you have created and this script is dependent on then, but some how there scripts are not available in this project as i have downloaded you project from GitHub, can you help with the issue in any way or kindly add those scripts to the project too for resolving these issues..

After resolving the packages issues : 
1st error : 
Assets\Globals\s_flagManager.cs(5,30): error CS0246: The type or namespace name 's_singleton<>' could not be found (are you missing a using directive or an assembly reference?)

2nd : 
Assets\Globals\s_flagManager.cs(17,31): error CS0246: The type or namespace name 'dat_globalflags' could not be found (are you missing a using directive or an assembly reference?)

3rd : 
Assets\Globals\s_flagManager.cs(47,26): error CS0246: The type or namespace name 'dat_globalflags' could not be found (are you missing a using directive or an assembly reference?)

4rth : 
Assets\Globals\s_flagManager.cs(7,17): error CS0246: The type or namespace name 'ev_integer' could not be found (are you missing a using directive or an assembly reference?)

**Comment by PixelBrownieSoftware** [comment]
I've updated the source code to include the dat_globalflags, ev_integer and s_singleton files.
The first two are in the dat_save file (located in Globals). For some reason, I forgot to put these files in from Magnum Foundation 2.
Thanks for expressing interest!
